[General]
languages=zh_CN

[6.0]
common\DefaultLanguage=2052
common\Local\UILanguage=2052
# 多组件独立模式（RPC 必需）
wpsoffice\Application%20Settings\AppComponentMode=prome_independ
wpsoffice\Application%20Settings\AppComponentModeInstall=prome_independ
# 接受 EULA
common\AcceptedEULA=true
# 禁用备份
common\Backup\EnableBackup=0
wps\Application%20Settings\AutoBackupEnabled=0
wps\Application%20Settings\ForceAutoBackupEnabled=0
wps\Application%20Settings\SQLSecurityCheck=0
